### ISSUE TITLE
where to specify the resolution code? 哪里可以强制要求视频清晰度？

### ISSUE THREAD

**Issue by djzts** [SCUTJcfeng/bilibiliVideoDownloader#3]
请问config里有强制要求视频清晰度的变量吗？

**Comment by SCUTJcfeng** [comment]
感谢关注，config没有配置清晰度相关配置，我看了下代码，应该在下面这里附近指定 https://github.com/SCUTJcfeng/bilibili-video-downloader/blob/419fe56f8a1d25362a5964c7bdf58eab72929efb/run.py#L130

这里会拿最高清晰度，当年最高是1080 60，现在可能不work了:)

**Comment by djzts** [comment]
十分感谢您的回答！thx!
